### PR TITLE
Making @SpecAssertion a repeatable annotation type

### PR DESCRIPTION
**Pull request by gunnarmorling**
Due to the move to Java 8 it's probably a good idea to bump the version to 1.2, too.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi @tremes, could you take a look at this one?

**Comment by tremes** [comment]
Merged. Thank you.

**Comment by gunnarmorling** [comment]
Nice, thanks! Do you think you could spin a release with this change some
time soon?

**Comment by tremes** [comment]
Yeah I think so ;-)

**Comment by gunnarmorling** [comment]
Cool, Bean Validation hugs you :)

**Pull request merged**
